apiVersion: batch/v1
kind: Job
metadata:
  name: trial-{{N_ESTIMATORS}}-{{MAX_DEPTH}}-{{LEARNING_RATE}}-{{SUBSAMPLE}}
  labels:
    app: xgb-hyperparameter-tuning
    trial: "true"
spec:
  template:
    metadata:
      labels:
        app: trial
        n_estimators: "{{N_ESTIMATORS}}"
        max_depth: "{{MAX_DEPTH}}"
        learning_rate: "{{LEARNING_RATE}}"
        subsample: "{{SUBSAMPLE}}"
    spec:
      containers:
      - name: xgb-trainer
        image: mannarn/model-train:latest
        args:
        - "--n_estimators={{N_ESTIMATORS}}"
        - "--max_depth={{MAX_DEPTH}}"
        - "--learning_rate={{LEARNING_RATE_RAW}}"
        - "--subsample={{SUBSAMPLE_RAW}}"
        volumeMounts:
        - name: data-volume
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: data-volume
        hostPath:
          path: /data
          type: DirectoryOrCreate