FROM python:3.8-slim

WORKDIR /app

# Copy files from the build context
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY app.py .
# Optionally, copy the best model file if it's already present;
# otherwise, your pipeline should update this file later.
COPY best_model.joblib .

CMD ["python", "app.py"]
